spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/real-world-db
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop