basePath: /api
info:
  contact: {}
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /users/login:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      - application/json
  /users/register:
    post:
      consumes:
      - application/json
      produces:
      - application/json
swagger: "2.0"
